#!/usr/bin/env python3
import sys
import argparse
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from pehchan.PehchanDatabase import PehchanDatabase

version = ''
try:
	version = pkg_resources.get_distribution("pehchan").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Create database',
	usage = 'pehchan [options] output_directory 1.fasta 2.fasta ...',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('output_directory', help='Output directory name (must not exist already)',type=str)
parser.add_argument('input_files', help='Input FASTA files (optionally gzipped)', nargs='+', type=str)

# Input
parser.add_argument('--kmerlength', '-k',  help='kmer', type=int, default=11)
parser.add_argument('--threads', '-t',  help='No. of threads to use', type=int, default=1)


# Advanced

parser.add_argument('--verbose', '-v', action='store_true', help='Turn on debugging', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

if options.verbose:
    import cProfile, pstats, io
    pr = cProfile.Profile()
    pr.enable()

    g = PehchanDatabase(options)
    g.run()

    pr.disable()
    s = io.StringIO()
    sortby = 'cumulative'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print(s.getvalue())
else:
    g = PehchanDatabase(options)
    g.run()
